export const DASHBOARD_CANDIDATES_SCHEMA = {
  type: "object",
  properties: {
    candidates: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          summary: { type: "string" },
          designIntent: { type: "string" },
          briefId: { type: "string" },
          purpose: { type: "string" },
          targetKpis: { type: "array", items: { type: "string" } },
          chartRoles: {
            type: "array",
            items: {
              type: "string",
              enum: ["summary", "trend", "breakdown", "ranking", "composition", "diagnostic", "detail", "relationship"],
            },
          },
          question: { type: "string" },
          viewpoint: { type: "string", enum: ["main_overview", "relationship", "detail_breakdown"] },
          sourceTableIds: { type: "array", items: { type: "string" } },
          mainTableId: { type: "string" },
          supportingTableIds: { type: "array", items: { type: "string" } },
          contextUsage: { type: "string" },
          visualizationPlan: {
            type: "array",
            items: {
              type: "object",
              properties: {
                id: { type: "string" },
                tableId: { type: "string" },
                chartType: {
                  type: "string",
                  enum: [
                    "kpi",
                    "bar",
                    "verticalBar",
                    "horizontalBar",
                    "groupedBar",
                    "rankingBar",
                    "line",
                    "pie",
                    "donut",
                    "comboBarLine",
                    "scatter",
                    "matrix",
                    "funnel",
                    "area",
                    "tableSummary",
                  ],
                },
                intent: {
                  type: "string",
                  enum: ["comparison", "trend", "composition", "stage_change", "relationship", "ranking", "summary"],
                },
                fields: {
                  type: "object",
                  properties: {
                    categoryField: { type: "string" },
                    valueField: { type: "string" },
                    barValueField: { type: "string" },
                    lineValueField: { type: "string" },
                    dateField: { type: "string" },
                    groupField: { type: "string" },
                    xField: { type: "string" },
                    yField: { type: "string" },
                  },
                },
                reason: { type: "string" },
                suitability: { type: "string", enum: ["high", "medium", "low"] },
              },
              required: ["id", "tableId", "chartType", "intent", "fields", "reason"],
            },
          },
          svgMarkup: { type: "string" },
          usedFields: { type: "array", items: { type: "string" } },
          notes: { type: "array", items: { type: "string" } },
        },
        required: [
          "id",
          "title",
          "summary",
          "designIntent",
          "briefId",
          "purpose",
          "targetKpis",
          "chartRoles",
          "question",
          "viewpoint",
          "sourceTableIds",
          "mainTableId",
          "supportingTableIds",
          "contextUsage",
          "visualizationPlan",
          "svgMarkup",
        ],
      },
    },
  },
  required: ["candidates"],
} as const;
