import type { ResolvedDocumentContext, ResolvedTable } from "@/schema/resolved_table";

export function buildDashboardBriefsPrompt({
  documentContext,
  tables,
}: {
  readonly documentContext: ResolvedDocumentContext;
  readonly tables: readonly ResolvedTable[];
}): string {
  return [
    "당신은 확정된 표 구조와 컬럼 타입 분석을 읽고 대시보드 후보 생성을 위한 전략 brief를 작성하는 데이터 제품 기획자입니다.",
    "정확히 하나의 유효한 JSON 객체만 반환하세요. Markdown 코드 블록은 사용하지 마세요.",
    "최상위 JSON 객체는 반드시 dashboardBriefs 배열을 가져야 합니다.",
    "",
    "핵심 목표:",
    "- 표에서 질문을 먼저 뽑지 마세요.",
    "- 먼저 이 데이터셋으로 어떤 목적의 대시보드를 만들 수 있는지 정의하세요.",
    "- 각 목적을 만족하기 위한 인사이트, KPI, chart role, role별 chart candidate를 한 번에 설계하세요.",
    "- chart candidate는 별도 차트 추천 단계가 아니라 dashboard brief에 귀속됩니다.",
    "- 데이터에 없는 의미, 단위, 수치, 순위, 인사이트를 임의로 만들지 마세요.",
    "- field 이름은 반드시 입력 table.columns 안의 값만 사용하세요.",
    "",
    "반환 형식:",
    "{",
    '  "dashboardBriefs": [',
    "    {",
    '      "id": "brief-1",',
    '      "title": "string",',
    '      "purposeType": "executive_overview | performance_monitoring | diagnostic_analysis | segment_comparison | trend_monitoring | detail_breakdown | relationship_analysis",',
    '      "purpose": "이 표로 만들 대시보드의 목적",',
    '      "audienceOrUseCase": "누가 어떤 의사결정에 쓰는지",',
    '      "primaryQuestion": "이 목적을 설명하는 보조 질문",',
    '      "summary": "100자 이내 요약",',
    '      "sourceTableIds": ["table id"],',
    '      "mainTableId": "table id",',
    '      "supportingTableIds": ["table id"],',
    '      "insights": [',
    '        { "id": "insight-1", "statement": "관찰한 핵심 패턴", "evidence": "근거가 되는 표/필드/행 설명", "tableIds": ["table id"], "priority": "high | medium | low" }',
    "      ],",
    '      "kpis": [',
    "        {",
    '          "id": "kpi-1",',
    '          "name": "KPI 이름",',
    '          "role": "primary | supporting | diagnostic | context",',
    '          "tableId": "table id",',
    '          "field": "numeric field",',
    '          "aggregation": "sum | average | count | min | max | latest | ratio | none",',
    '          "calculation": "입력 데이터로 계산 가능한 방식",',
    '          "reason": "이 목적에 필요한 이유",',
    '          "unit": "string"',
    "        }",
    "      ],",
    '      "chartRoles": [',
    "        {",
    '          "id": "role-1",',
    '          "role": "summary | trend | breakdown | ranking | composition | diagnostic | detail | relationship",',
    '          "title": "역할 이름",',
    '          "purpose": "대시보드 안에서 이 블록이 맡는 시각적 역할",',
    '          "question": "이 역할이 답하는 보조 질문",',
    '          "priority": "high | medium | low",',
    '          "tableIds": ["table id"],',
    '          "requiredKpis": ["kpi-1"],',
    '          "chartCandidates": [',
    "            {",
    '              "id": "chart-candidate-1",',
    '              "tableId": "table id",',
    '              "chartType": "kpi | bar | verticalBar | horizontalBar | groupedBar | rankingBar | line | pie | donut | comboBarLine | scatter | matrix | funnel | area | tableSummary",',
    '              "intent": "comparison | trend | composition | stage_change | relationship | ranking | summary",',
    '              "suitability": "high | medium | low",',
    '              "fields": { "primaryMeasure": "numeric field", "secondaryMeasure": "numeric field", "category": "category field", "date": "date field", "group": "group field", "x": "field", "y": "field" },',
    '              "reason": "이 role을 구현하기에 적합한 이유",',
    '              "risks": ["string"]',
    "            }",
    "          ]",
    "        }",
    "      ],",
    '      "candidateStrategy": "이 brief가 어떤 대시보드 후보로 조립되어야 하는지"',
    "    }",
    "  ]",
    "}",
    "",
    "brief 생성 규칙:",
    "- dashboardBriefs는 정확히 3개를 생성하세요.",
    "- 세 brief는 목적이 달라야 합니다. 단순히 질문만 바꾸지 마세요.",
    "- 후보 1은 가능하면 전체 성과나 현황을 요약하는 목적입니다.",
    "- 후보 2는 표 간 관계가 유효하면 relationship_analysis, 그렇지 않으면 diagnostic_analysis 또는 segment_comparison입니다.",
    "- 후보 3은 세부 breakdown, ranking, composition, detail 중심 목적입니다.",
    "- 각 brief에는 high priority chartRole을 최소 2개 포함하세요.",
    "- 각 chartRole에는 chartCandidates를 1~3개 포함하세요.",
    "- chartCandidates는 현재 데이터와 필드로 실제 구현 가능한 후보만 작성하세요.",
    "",
    "차트 후보 판단 규칙:",
    "- numericColumns는 값/측정값 후보입니다.",
    "- categoryColumns는 범주/분류/그룹 후보입니다.",
    "- dateColumns는 추세 축 후보입니다.",
    "- tableShape=timeSeries이면 trend role에 line 또는 comboBarLine을 검토하세요.",
    "- tableShape=ranking이면 ranking role에 rankingBar를 우선 검토하세요.",
    "- tableShape=categoryBreakdown이면 breakdown/composition role에 bar, rankingBar, pie, donut을 검토하세요.",
    "- tableShape=metricList이면 summary role에 kpi 또는 tableSummary를 검토하세요.",
    "- tableShape=funnel이면 diagnostic 또는 stage_change 목적에 funnel을 검토하세요.",
    "- 행이 2개 미만이면 line을 추천하지 마세요.",
    "- 범주가 너무 많으면 pie/donut보다 rankingBar를 우선 추천하세요.",
    "- 긴 라벨이나 많은 항목은 rankingBar에 적합합니다.",
    "- 비율/구성비를 보여줄 때만 pie/donut을 추천하세요.",
    "- comboBarLine은 두 지표가 같은 x축을 공유하고 함께 해석할 가치가 있을 때만 추천하세요.",
    "- comboBarLine의 fields에는 primaryMeasure, secondaryMeasure, date 또는 category를 반드시 포함하세요.",
    "- 현재 안정 렌더링 차트는 kpi, bar, rankingBar, line, comboBarLine입니다.",
    "- pie/donut/funnel/tableSummary/scatter/matrix/area는 SVG preview 관점의 후보로만 제한적으로 제안하세요.",
    "",
    "documentContext 사용 규칙:",
    "- documentContext.title과 summary를 전체 주제 판단 기준으로 사용하세요.",
    "- documentContext.relationships 중 usableForCombinedDashboard=true인 관계만 여러 표를 한 brief에 결합하는 근거로 사용하세요.",
    "- usableForCombinedDashboard=false이면 같은 주제라도 한 brief에서 억지로 cross-table 메시지를 만들지 마세요.",
    "",
    "[파일 전체 맥락]",
    JSON.stringify(documentContext, null, 2),
    "",
    "[확정된 표 정보]",
    JSON.stringify(
      tables.map((table) => ({
        id: table.id,
        tableShape: table.tableShape,
        title: table.title,
        context: table.context,
        columns: table.columns,
        analysis: table.analysis,
        rows: table.rows,
      })),
      null,
      2,
    ),
  ].join("\n");
}
