import type { ResolvedDocumentContext, ResolvedTable } from "@/schema/resolved_table";
import type { TableChartOptionGroup } from "@/schema/table_chart_option";

export function buildDashboardCandidatesPrompt({
  documentContext,
  tables,
  chartOptionsByTable,
}: {
  readonly documentContext: ResolvedDocumentContext;
  readonly tables: readonly ResolvedTable[];
  readonly chartOptionsByTable: readonly TableChartOptionGroup[];
}): string {
  return [
    "당신은 표 데이터를 분석하여 고품질 인포그래픽 대시보드를 SVG로 직접 설계하는 데이터 시각화 디자이너입니다.",
    "정확히 하나의 유효한 JSON 객체만 반환하세요. Markdown 코드 블록은 사용하지 마세요.",
    "최상위 JSON 객체는 반드시 candidates 배열을 가져야 합니다.",
    "후보는 정확히 3개만 생성하세요.",
    "각 후보는 title, summary, designIntent, question, viewpoint, sourceTableIds, mainTableId, supportingTableIds, contextUsage, visualizationPlan, svgMarkup, usedFields, notes를 가져야 합니다.",
    "summary는 100자 이내로 작성하세요.",
    "",
    "반환 형식:",
    "{",
    '  "candidates": [',
    "    {",
    '      "id": "candidate-1",',
    '      "title": "string",',
    '      "summary": "string",',
    '      "designIntent": "string",',
    '      "question": "string",',
    '      "viewpoint": "main_overview | relationship | detail_breakdown",',
    '      "sourceTableIds": ["table id"],',
    '      "mainTableId": "table id",',
    '      "supportingTableIds": ["table id"],',
    '      "contextUsage": "string",',
    '      "visualizationPlan": [',
    "        {",
    '          "id": "viz-1",',
    '          "tableId": "table id",',
    '          "chartType": "kpi | bar | verticalBar | horizontalBar | groupedBar | rankingBar | line | pie | donut | comboBarLine | scatter | matrix | funnel | area | tableSummary",',
    '          "intent": "comparison | trend | composition | stage_change | relationship | ranking | summary",',
    '          "fields": { "categoryField": "string", "valueField": "string", "barValueField": "string", "lineValueField": "string", "dateField": "string", "groupField": "string", "xField": "string", "yField": "string" },',
    '          "reason": "string",',
    '          "suitability": "high | medium | low"',
    "        }",
    "      ],",
    '      "svgMarkup": "string",',
    '      "usedFields": ["string"],',
    '      "notes": ["string"]',
    "    }",
    "  ]",
    "}",
    "",
    "작업 순서:",
    "1. 먼저 [파일 전체 맥락], [확정된 표 정보], [표별 시각화 후보]를 읽고 데이터 주제, 표별 맥락, 표 간 관계를 파악하세요.",
    "2. [표별 시각화 후보]의 lens와 chartOptions 중에서 후보 대시보드 관점에 맞는 조합을 선택하세요.",
    "3. 데이터로 답할 수 있는 분석 질문 3개를 도출하세요.",
    "4. 각 질문에 맞춰 후보 3개의 viewpoint를 다르게 설정하세요.",
    "5. 각 후보마다 사용할 표, 필드, 차트 유형을 visualizationPlan에 먼저 기록하세요.",
    "6. 마지막에 visualizationPlan을 기준으로 svgMarkup을 생성하세요.",
    "7. svgMarkup에 표현한 모든 차트는 반드시 visualizationPlan에도 같은 chartType과 fields로 포함되어야 합니다.",
    "",
    "표별 시각화 후보 사용 규칙:",
    "- 새 차트 후보를 임의로 만들지 말고 [표별 시각화 후보]의 chartOptions 중에서 선택하세요.",
    "- visualizationPlan의 tableId, chartType, intent, fields는 선택한 chartOptions와 일치해야 합니다.",
    "- fields.primaryMeasure는 visualizationPlan.fields.valueField에 대응합니다.",
    "- comboBarLine에서는 fields.primaryMeasure를 visualizationPlan.fields.barValueField에, fields.secondaryMeasure를 visualizationPlan.fields.lineValueField에 대응하세요.",
    "- fields.category는 visualizationPlan.fields.categoryField에 대응합니다.",
    "- fields.date는 visualizationPlan.fields.dateField에 대응합니다.",
    "- fields.group은 visualizationPlan.fields.groupField에 대응합니다.",
    "- fields.x는 visualizationPlan.fields.xField에 대응합니다.",
    "- fields.y는 visualizationPlan.fields.yField에 대응합니다.",
    "- main_overview는 priority=high lens와 renderSupport=stable chartOptions를 우선 사용하세요.",
    "- relationship은 documentContext.relationships와 호환되는 여러 table lens를 조합하세요.",
    "- detail_breakdown은 ranking, composition, comparison lens를 우선 사용하세요.",
    "- renderSupport=unsupported인 chartOptions는 다른 대안이 전혀 없을 때만 SVG 장식 수준으로 사용하세요.",
    "- comboBarLine을 선택한 경우 막대는 절대값 지표, 선은 추세/비율/보조 지표로 표현하고, 축/범례/단위 차이를 SVG 안에 명확히 표시하세요.",
    "- SVG에 comboBarLine 형태(막대+선)를 그렸다면 visualizationPlan에도 반드시 chartType=comboBarLine 항목을 포함하세요.",
    "- 사용한 lens id와 chart option id는 notes에 짧게 남기세요.",
    "",
    "작업 목표:",
    "- 입력된 표 데이터를 기반으로 서로 다른 관점의 인포그래픽 대시보드 후보 3개를 생성하세요.",
    "- 각 후보는 하나의 완성형 SVG 대시보드 페이지여야 합니다.",
    "- 데이터에 없는 수치, 항목명, 연도, 비율, 순위, 인사이트를 임의로 만들지 마세요.",
    "",
    "documentContext 사용 규칙:",
    "- documentContext.title과 summary를 후보의 전체 주제 판단 기준으로 사용하세요.",
    "- documentContext.tableContexts는 각 표가 무엇을 설명하는지 이해하는 참고 정보입니다.",
    "- mainTableId와 supportingTableIds는 tableContexts의 설명만으로 고정하지 말고, 실제 columns, rows, analysis, relationships를 함께 보고 선택하세요.",
    "- documentContext.relationships 중 usableForCombinedDashboard=true인 관계만 여러 표를 한 후보에 결합하는 근거로 사용하세요.",
    "- usableForCombinedDashboard=true인 관계가 있으면 후보 3개 중 최소 1개는 viewpoint=relationship으로 만들고 해당 관계의 tableIds를 sourceTableIds에 포함하세요.",
    "- type=independent 또는 usableForCombinedDashboard=false인 관계는 결합 후보 근거로 사용하지 마세요. 이 경우 표별 독립 질문이나 detail_breakdown 후보로 분리하세요.",
    "- type=shared_subject이지만 usableForCombinedDashboard=false이면 같은 주제의 독립 표로 보고, 한 화면에서 억지로 cross-table 메시지를 만들지 마세요.",
    "",
    "후보 3개 구성 규칙:",
    "- 후보 1은 가능하면 viewpoint=main_overview로 만들고 main 표 중심으로 전체 핵심 메시지를 보여주세요.",
    "- 후보 2는 표 간 관계가 유효하면 viewpoint=relationship으로 만들고, 그렇지 않으면 주요 표 내부의 지표 관계나 비교 질문으로 구성하세요.",
    "- 후보 3은 viewpoint=detail_breakdown으로 만들고 세부 구조, 순위, 구성비, 제품군/항목별 차이를 보여주세요.",
    "- 세 후보는 질문, 관점, 레이아웃, 정보 위계가 달라야 합니다.",
    "",
    "시각화 설계 규칙:",
    "- 데이터가 말하는 핵심 메시지를 먼저 파악하세요.",
    "- 각 후보는 핵심 메시지를 가장 잘 전달하는 시각 표현을 선택하세요.",
    "- 수치의 크기 비교, 순위, 흐름, 구성비, 단계 변화, 격차, 집중도, 이상값 중 무엇을 보여줄지 판단하세요.",
    "- 표는 사용자가 한눈에 이해할 수 있도록 요약·비교·강조 구조로 재구성하세요.",
    "- 하나의 화면에 너무 많은 차트를 넣지 마세요.",
    "- 모든 시각 요소는 입력 데이터에 근거해야 합니다.",
    "",
    "디자인 요구사항:",
    "- 보고서형 인포그래픽 대시보드처럼 보여야 합니다.",
    "- 카드형 패널, 라운드 박스, 그림자, 그라데이션, 아이콘형 도형, 큰 숫자 타이포그래피를 활용하세요.",
    "- 전체 결과는 하나의 완성된 dashboard page처럼 보여야 합니다.",
    "- 단순 차트 하나만 배치한 SVG는 실패입니다.",
    "- 차트가 없는 대시보드는 실패입니다.",
    "- 중앙에 작은 그래프만 있는 SVG는 실패입니다.",
    "- 미리보기 카드 안에서도 핵심 구조와 핵심 숫자가 보이도록 큰 요소 중심으로 구성하세요.",
    "- 너무 작은 보조 텍스트를 과도하게 넣지 마세요.",
    "",
    "레이아웃 안전 규칙:",
    "- SVG는 width='1122' height='1402' viewBox='0 0 1122 1402' 기준으로 작성하세요.",
    "- 1122x1402 전체 캔버스를 적극적으로 사용하세요.",
    "- 텍스트가 캔버스 밖으로 나가지 않게 하세요.",
    "- 차트가 패널 또는 캔버스 밖으로 잘리면 실패입니다.",
    "- 차트 라벨이 겹치지 않도록 충분한 간격을 두세요.",
    "- 막대, 점, 선 등 차트 요소는 지정된 차트 영역 내부에만 배치하세요.",
    "- 긴 텍스트는 줄바꿈하거나 짧게 요약하세요.",
    "- 후보 미리보기에서 읽기 어려울 정도로 작은 글자를 남발하지 마세요.",
    "",
    "SVG 안전 규칙:",
    "- SVG 외부 HTML/CSS/JS를 만들지 마세요.",
    "- script, foreignObject, iframe, image, use, animate, set을 사용하지 마세요.",
    "- onClick, onLoad 등 이벤트 속성을 사용하지 마세요.",
    "- 외부 URL, javascript:, href, xlink:href 외부 참조를 사용하지 마세요.",
    "- style 태그, style 속성, class 속성을 사용하지 마세요.",
    "- 모든 스타일은 fill, stroke, opacity, font-size, font-weight 등 SVG presentation attribute로 작성하세요.",
    "- defs, linearGradient, radialGradient, stop, filter, feDropShadow, feGaussianBlur, feOffset, feColorMatrix는 사용할 수 있습니다.",
    "- url(#id) 형태의 내부 참조만 허용됩니다.",
    "- XML 특수문자는 안전하게 이스케이프하세요.",
    "- 텍스트 안의 &, <, > 문자는 XML 파싱 오류가 나지 않도록 처리하세요.",
    "",
    "데이터 규칙:",
    "- 입력 표에 없는 수치나 항목을 임의로 만들지 마세요.",
    "- 차트와 KPI 숫자는 입력 표 데이터에 기반해야 합니다.",
    "- 계산이 필요한 경우 입력 데이터로부터 직접 계산 가능한 값만 사용하세요.",
    "- 계산한 값은 notes에 계산 근거를 짧게 남기세요.",
    "- 불확실한 값은 만들지 말고 제외하세요.",
    "",
    "실패 후보 기준:",
    "- 차트가 잘리는 후보",
    "- 차트 의미가 불명확한 후보",
    "- 동일한 차트로 구성된 후보",
    "- 항목명, 단위, 범례 없이 도형만 배치한 후보",
    "- 데이터 필드에 없는 값을 만든 후보",
    "- 제목과 차트 내용이 맞지 않는 후보",
    "- 여러 분석 질문을 한 화면에 무리하게 섞은 후보",
    "- 데이터 맥락보다 장식이 우선된 후보",
    "- 값의 상대적 크기가 시각적으로 반대로 표현된 후보",
    "",
    "[파일 전체 맥락]",
    JSON.stringify(documentContext, null, 2),
    "",
    "[표별 시각화 후보]",
    JSON.stringify(chartOptionsByTable, null, 2),
    "",
    "[확정된 표 정보]",
    JSON.stringify(
      tables.map((table) => ({
        id: table.id,
        tableShape: table.tableShape,
        title: table.title,
        context: table.context,
        columns: table.columns,
        analysis: table.analysis,
        rows: table.rows,
      })),
      null,
      2,
    ),
  ].join("\n");
}
