import type { ParsedCsvGrid } from "@/lib/data/parse_csv";

export function buildResolveTablesPrompt({ grid }: { readonly grid: ParsedCsvGrid }): string {
  return [
    "당신은 CSV grid를 읽고 표/메모/메타데이터 영역을 분리하는 문서 구조 해석기입니다.",
    "정확히 하나의 유효한 JSON 객체만 반환하세요. Markdown 코드 블록은 사용하지 마세요.",
    "모든 row/col 좌표는 0-based 인덱스입니다.",
    "셀 값 자체를 복사/변형하지 말고, 영역 좌표와 의미만 판정하세요.",
    "kind는 table, note, metadata, titleBlock 중 하나여야 합니다.",
    "실제 데이터 표만 kind=table로 반환하세요.",
    "kind=table이면 tableShape를 반드시 지정하세요.",
    "kind가 table이 아니면 tableShape는 null로 반환하세요.",
    "tableShape는 records, metricList, timeSeries, ranking, categoryBreakdown, crossTab, funnel, lookup 중 하나입니다.",
    "records: 일반 행 단위 데이터입니다.",
    "metricList: 지표명-값 형태의 KPI 목록입니다.",
    "timeSeries: 날짜/기간 축이 명확한 시계열입니다.",
    "ranking: 순위 또는 Top-N 구조입니다.",
    "categoryBreakdown: 하나의 전체를 범주별로 분해한 구조입니다.",
    "crossTab: 행/열 양쪽이 의미 있는 피벗형 표입니다.",
    "funnel: 단계별 전환/감소 흐름입니다.",
    "lookup: 코드/명칭/설명 매핑용 보조 표입니다.",
    "kind=table이면 headerRow, dataStartRow, dataEndRow를 반드시 지정하세요.",
    "headerRow는 dataStartRow보다 반드시 작아야 합니다.",
    "한 table은 하나의 연속된 직사각형 범위(range)만 가져야 합니다.",
    "title과 context는 짧고 명확하게 작성하세요.",
    "confidence는 0~1 사이 값입니다.",
    "빈 줄, 제목 행, 반복 헤더, 주석/메타데이터 영역, 실제 데이터 본문을 구분하세요.",
    "표가 여러 개면 모두 반환하세요.",
    "",
    "추가로 documentContext를 작성하세요.",
    "- title: 파일 전체 제목을 30자 이내로 추정하세요.",
    "- summary: 파일 전체 주제와 데이터 성격을 120자 이내로 요약하세요.",
    "- tableContexts: 각 table id가 파일 전체 맥락에서 무엇을 설명하는지 한 문장으로 작성하세요.",
    "- tableContexts에는 역할 분류나 중요도 판단을 넣지 마세요.",
    "- relationships: 진짜 표 간 관계가 있거나, 같은 파일 안의 독립 표라는 점을 후속 판단에 남겨야 할 때만 작성하세요.",
    "- relationship.type은 cross_table, supporting_context, independent, shared_subject, breakdown 중 하나입니다.",
    "- cross_table: 한 표의 값이 다른 표의 지표와 직접 결합/비교/계산될 수 있는 관계입니다.",
    "- supporting_context: 한 표가 다른 표의 해석 배경이나 보조 설명으로 쓰이는 관계입니다.",
    "- shared_subject: 같은 주제를 다루지만 직접 결합할 공통 key나 분석 축은 약한 관계입니다.",
    "- breakdown: 한 표가 다른 표의 하위 구성, 세부 분해, drill-down인 관계입니다.",
    "- independent: 같은 파일 안에 있지만 서로 다른 사업 지표를 보여주는 독립 표입니다.",
    "- usableForCombinedDashboard는 cross_table 또는 breakdown처럼 한 후보 안에서 같이 시각화해도 의미가 명확할 때만 true로 설정하세요.",
    "- independent 또는 shared_subject처럼 결합이 애매한 관계는 usableForCombinedDashboard=false로 설정하세요.",
    "- confidence는 0~1 사이 값입니다. 관계가 불확실하면 relationships에 넣지 말거나 confidence를 낮게 두고 usableForCombinedDashboard=false로 설정하세요.",
    "- documentContext는 후속 대시보드 후보 생성에서 파일 전체 주제, 표별 맥락, 표 간 결합 가능성을 판단하는 참고 정보로 사용됩니다.",
    "[Grid 정보]",
    JSON.stringify({
      rowCount: grid.rowCount,
      columnCount: grid.columnCount,
      rows: grid.rows.map((cells, row) => ({ row, cells })),
    }, null, 2),
  ].join("\n");
}
