import type { ResolvedDocumentContext, ResolvedTable } from "@/schema/resolved_table";

export function buildTableChartOptionsPrompt({
  documentContext,
  tables,
}: {
  readonly documentContext: ResolvedDocumentContext;
  readonly tables: readonly ResolvedTable[];
}): string {
  return [
    "당신은 확정된 표 구조와 컬럼 타입 분석을 읽고 표별 시각화 후보를 도출하는 데이터 시각화 전략가입니다.",
    "정확히 하나의 유효한 JSON 객체만 반환하세요. Markdown 코드 블록은 사용하지 마세요.",
    "최상위 JSON 객체는 반드시 chartOptionsByTable 배열을 가져야 합니다.",
    "",
    "목표:",
    "- 표마다 하나의 최적 차트만 고르지 마세요.",
    "- 같은 표 안에서도 관점이 다르면 여러 lens를 만드세요.",
    "- 각 lens는 무엇을 알고 싶은지에 대한 분석 질문(question)을 가져야 합니다.",
    "- 각 lens마다 중점 컬럼, 행 범위, 중요한 셀, 가능한 차트 후보를 기록하세요.",
    "- 데이터에 없는 의미, 단위, 수치, 순위, 인사이트를 임의로 만들지 마세요.",
    "- field 이름은 반드시 입력 table.columns 안의 값만 사용하세요.",
    "- rows의 배열 인덱스는 표 내부 데이터 행 기준 0-based 인덱스로 사용하세요.",
    "",
    "반환 형식:",
    "{",
    '  "chartOptionsByTable": [',
    "    {",
    '      "tableId": "table id",',
    '      "tableRole": "primary | supporting | lookup | context",',
    '      "tableSummary": "string",',
    '      "lenses": [',
    "        {",
    '          "id": "lens-1",',
    '          "question": "이 관점이 답하려는 질문",',
    '          "focus": "overview | trend | ranking | composition | comparison | relationship | outlier | kpi | stage_change",',
    '          "subject": "무엇을 중심으로 보는지",',
    '          "priority": "high | medium | low",',
    '          "fields": {',
    '            "primaryMeasure": "numeric field",',
    '            "secondaryMeasure": "numeric field",',
    '            "category": "category field",',
    '            "date": "date field",',
    '            "group": "group field",',
    '            "x": "field",',
    '            "y": "field"',
    "          },",
    '          "evidence": {',
    '            "rowScope": "all_rows | top_n | latest | filtered | specific_rows",',
    '            "rowIndexes": [0, 1],',
    '            "filterDescription": "string",',
    '            "importantCells": [',
    '              { "rowIndex": 0, "field": "field name", "role": "max | min | latest | total | label | comparison_base | notable", "reason": "string" }',
    "            ]",
    "          },",
    '          "chartOptions": [',
    "            {",
    '              "id": "chart-option-1",',
    '              "chartType": "kpi | bar | verticalBar | horizontalBar | groupedBar | rankingBar | line | pie | donut | comboBarLine | scatter | matrix | funnel | area | tableSummary",',
    '              "intent": "comparison | trend | composition | stage_change | relationship | ranking | summary",',
    '              "suitability": "high | medium | low",',
    '              "fields": { "primaryMeasure": "numeric field", "category": "category field" },',
    '              "reason": "왜 이 lens에 적합한지",',
    '              "risks": ["string"]',
    "            }",
    "          ]",
    "        }",
    "      ]",
    "    }",
    "  ]",
    "}",
    "",
    "판단 규칙:",
    "- numericColumns는 값/측정값 후보입니다.",
    "- categoryColumns는 범주/분류/그룹 후보입니다.",
    "- dateColumns는 추세 축 후보입니다.",
    "- tableShape=timeSeries이면 trend lens를 우선 검토하세요.",
    "- tableShape=ranking이면 ranking lens를 우선 검토하세요.",
    "- tableShape=categoryBreakdown이면 composition과 comparison lens를 검토하세요.",
    "- tableShape=metricList이면 kpi와 tableSummary lens를 검토하세요.",
    "- tableShape=funnel이면 stage_change lens를 검토하세요.",
    "- lookup 표는 차트 후보를 만들기보다 다른 표의 해석 보조로 분류하세요.",
    "- 행이 2개 미만이면 line을 추천하지 마세요.",
    "- 범주가 너무 많으면 pie/donut보다 rankingBar를 우선 추천하세요.",
    "- 긴 라벨이나 많은 항목은 rankingBar에 적합합니다.",
    "- 비율/구성비를 보여줄 때만 pie/donut을 추천하세요.",
    "- comboBarLine은 아래 조건을 모두 만족할 때만 추천하세요.",
    "  1) 두 지표가 같은 x축(date 또는 category)을 공유합니다.",
    "  2) primaryMeasure는 막대로 표현할 절대값 지표입니다.",
    "  3) secondaryMeasure는 선으로 표현할 추세/비율/보조 지표입니다.",
    "  4) 두 지표를 함께 보면 해석 가치가 있습니다.",
    "  5) 두 지표가 같은 tableId의 같은 row 기준으로 정렬 가능합니다.",
    "- comboBarLine을 추천할 때 fields에는 primaryMeasure, secondaryMeasure, date 또는 category를 반드시 포함하세요.",
    "- 단순히 numericColumns가 2개 있다는 이유만으로 comboBarLine을 추천하지 마세요.",
    "- 현재 안정 렌더링 차트는 kpi, bar, rankingBar, line, comboBarLine입니다.",
    "- pie/donut/funnel/tableSummary/scatter/matrix/area는 SVG preview 관점의 후보로만 제한적으로 제안하세요.",
    "- 각 table의 lens는 가능하면 2~5개로 제한하세요.",
    "- 각 lens의 chartOptions는 가능하면 1~3개로 제한하세요.",
    "",
    "[파일 전체 맥락]",
    JSON.stringify(documentContext, null, 2),
    "",
    "[확정된 표 정보]",
    JSON.stringify(
      tables.map((table) => ({
        id: table.id,
        tableShape: table.tableShape,
        title: table.title,
        context: table.context,
        columns: table.columns,
        analysis: table.analysis,
        rows: table.rows,
      })),
      null,
      2,
    ),
  ].join("\n");
}
